server:
  port: 8090
  servlet:
    context-path: /

spring:
  application:
    name: zentao4j


logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    com.laolang.shop: info
  config: classpath:logback-spring.xml
  file:
    path: ../logs/shop


